### PR TITLE
Issues #195, #184

### PR DESCRIPTION
**Pull request by marko-md**
@simonredfern Please consider the changes
Note that new property #mail.api.consumer.registered.notification.send=true can be omitted, set to true or set to false. Only set to true will trigger mail sending.

### CODE REVIEW

**Comment by simonredfern** [comment]
Please set sample
mail.api.consumer.registered.notification.send=false

**Comment by marko-md** [comment]
Currently it is under the comment i.e. omitted in props file.

**Comment by marko-md** [comment]
Do I have to:
- uncomment and set to false
- or just set to false?

**Comment by simonredfern** [comment]
Just set to false

**Pull request merged**
